import 'package:flutter/material.dart';

const kMainColor = Color(0xffffc12f);
const blue = Color(0xff003cff);
const kSecondaryColor = Color(0xFFFFE6AC);
const white = Color(0xFFFFFFFF);
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const kProductsCollection = 'Products';
const kUnActiveColor = Color(0xFFC1BDB8);
const kJackets = 'jackets';
const kTrousers = 'trousers';
const kTshirts = 't-shirts';
const kShoes = 'shoes';
const kOrders = 'Orders';
const kOrderDetails = 'OrderDetails';
const kTotallPrice = 'TotallPrice';
const kAddress = 'Address';
const kIsConfirmed = 'isConfirmed';
const kProductQuantity = 'Quantity';
const kKeepMeLoggedIn = 'KeepMeLoggedIn';
const kProductsToCartCollection = 'ProductsToCart';
const kUser = 'User Cart';
const kUserId = 'UserId';
